export const teamMembers = [
  {
    id: 1,
    name: "Aby Raoul",
    position: "Maire de Marcory",
    image: "/assets/images/illustrations/conseil-municipal/team1.jpeg",
    email: "maire@mairie-marcory.ci",
    phone: "+225 27 21 25 30 40",
  },
  {
    id: 2,
    name: "Traoré Mamadou",
    position: "1er Adjoint au Maire",
    image: "/assets/images/illustrations/conseil-municipal/team2.jpg",
    email: "adjoint@mairie-marcory.ci",
    phone: "+225 27 21 25 30 41",
  },
  {
    id: 3,
    name: "Koffi Adjoua",
    position: "Conseillère Municipale",
    image: "/assets/images/illustrations/conseil-municipal/team3.jpg",
    email: "conseillere1@mairie-marcory.ci",
    phone: "+225 27 21 25 30 42",
  },
  {
    id: 4,
    name: "Ouattara Ibrahim",
    position: "Conseiller Municipal",
    image: "/assets/images/illustrations/conseil-municipal/team6.jpg",
    email: "conseiller1@mairie-marcory.ci",
    phone: "+225 27 21 25 30 43",
  },
  {
    id: 5,
    name: "Yao Brigitte",
    position: "Secrétaire Générale de Mairie",
    image: "/assets/images/illustrations/conseil-municipal/team4.jpg",
    email: "secretaire@mairie-marcory.ci",
    phone: "+225 27 21 25 30 44",
  },
  {
    id: 6,
    name: "Bamba Aïssata",
    position: "Conseillère Municipale",
    image: "/assets/images/illustrations/conseil-municipal/team5.jpg",
    email: "conseillere2@mairie-marcory.ci",
    phone: "+225 27 21 25 30 45",
  },
  {
    id: 7,
    name: "Koné Moussa",
    position: "Conseiller Municipal",
    image: "/assets/images/illustrations/conseil-municipal/team6.jpg",
    email: "conseiller2@mairie-marcory.ci",
    phone: "+225 27 21 25 30 46",
  },
  {
    id: 8,
    name: "Diabaté Seydou",
    position: "Directeur Général des Services",
    image: "/assets/images/illustrations/conseil-municipal/team7.jpg",
    email: "directeur@mairie-marcory.ci",
    phone: "+225 27 21 25 30 47",
  },
]
